[project]
name = "nd2-timelapse-analyzer"
version = "0.1.0"
description = ""
authors = [{ name = "Henrique Hiram" }]
requires-python = ">=3.10,<3.12"
readme = "README.md"
license = { text = "LGPL" }
dependencies = [
    "pyside6 (==6.7.2)",
    "tensorflow (==2.15.0); sys_platform == 'linux' or sys_platform == 'win32'",
    "tensorflow-macos (==2.15.0); sys_platform == 'darwin' and platform_machine == 'arm64'",
    "tensorflow-io-gcs-filesystem (==0.31.0); sys_platform == 'win32'",
    "tensorflow-io-gcs-filesystem (>=0.37.1); sys_platform == 'linux' or (sys_platform == 'darwin' and platform_machine == 'arm64')",
    "polars (>=1.30.0,<2.0.0)",
    "nd2 (>=0.10.3,<0.11.0)",
    "opencv-python (>=4.11.0.86,<5.0.0.0)",
    "keras-applications (==1.0.8)",
    "imageio (>=2.37.0,<3.0.0)",
    "tifffile (<2024); sys_platform == 'linux'",
    "zarr (>=2.17.0,<3.0.0); sys_platform == 'linux'",
    "matplotlib (>=3.10.3,<4.0.0)",
    "pandas (>=2.2.3,<3.0.0)",
    "scikit-image (>=0.25.2,<0.26.0)",
    "scikit-learn (>=1.6.1,<2.0.0)",
    "pypubsub (>=4.0.3,<5.0.0)",
    "cachier (>=3.1.2,<4.0.0)",
    "omnipose (>=1.0.6,<2.0.0)",
    "scipy (==1.11.4)",
    "torch (==2.3.1); sys_platform == 'win32'",
    "torch (>=2.7.0,<3.0.0); sys_platform != 'win32'",
    "natsort (>=8.4.0,<9.0.0)",
    "vulture (>=2.14,<3.0)",
    "cellpose (>=4.0.6,<5.0.0)",
    "av (>=15.0.0,<16.0.0)",
    "imageio-ffmpeg (>=0.6.0,<0.7.0)",
    "numba (>=0.61.2,<0.62.0)",
    "seaborn>=0.13.2",
    "pyarrow>=21.0.0",
    "btrack (>=0.6.5,<0.7.0)",
    "lxml>=5.0",
    "zarr>=2.18.3",
]

[project.gui-scripts]
gui = "nd2_analyzer:main"

[tool.uv]
package = true
cache-dir = ".uv-cache"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/nd2_analyzer"]